const http = require('http');
const fs = require('fs');
const path = require('path');
const { exec, spawn, execSync } = require('child_process');
const { Client } = require('ssh2');
const os = require('os');
const events = require('events');

const PORT = 3456;
const GLOBAL_DIR = path.join(os.homedir(), '.gemini-bridge');
const CONFIGS_DIR = path.join(GLOBAL_DIR, 'configs');
const SETTINGS_FILE = path.join(GLOBAL_DIR, 'settings.json');
const GLOBAL_BIN_DIR = path.join(GLOBAL_DIR, 'bin');

if (!fs.existsSync(CONFIGS_DIR)) fs.mkdirSync(CONFIGS_DIR, { recursive: true });
if (!fs.existsSync(GLOBAL_BIN_DIR)) fs.mkdirSync(GLOBAL_BIN_DIR, { recursive: true });

// Sincronizar scripts al directorio global
function syncScripts() {
    const scriptsSrc = path.join(__dirname, 'scripts');
    if (!fs.existsSync(scriptsSrc)) return;
    
    const files = fs.readdirSync(scriptsSrc);
    files.forEach(f => {
        const src = path.join(scriptsSrc, f);
        const dest = path.join(GLOBAL_BIN_DIR, f);
        if (fs.lstatSync(src).isFile()) {
            fs.copyFileSync(src, dest);
            fs.chmodSync(dest, 0o755); // Asegurar ejecución
        }
    });
}
syncScripts();

// Ajustes iniciales
let globalSettings = { 
    intercept_terminal: false,
    instruction_filename: 'GEMINI.md' 
};

if (fs.existsSync(SETTINGS_FILE)) {
    try { 
        const saved = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8')); 
        globalSettings = { ...globalSettings, ...saved };
    } catch(e) {
        console.error("Error loading settings:", e);
    }
}

const logEmitter = new events.EventEmitter();
let activeSshSessions = {}; // Rastrear sesiones SSH activas por nombre
let mutagenCache = { output: '', lastUpdate: 0 };

async function getMutagenStatus() {
    const NOW = Date.now();
    if (NOW - mutagenCache.lastUpdate < 1000) return mutagenCache.output;
    
    return new Promise((resolve) => {
        exec('mutagen sync list', (err, stdout) => {
            mutagenCache.output = stdout || '';
            mutagenCache.lastUpdate = Date.now();
            resolve(mutagenCache.output);
        });
    });
}

function ensureSshKey() {
    const sshDir = path.join(os.homedir(), '.ssh');
    const keyPath = path.join(sshDir, 'id_ed25519_bridge');
    if (!fs.existsSync(sshDir)) fs.mkdirSync(sshDir, { recursive: true, mode: 0o700 });
    if (!fs.existsSync(keyPath)) {
        logEmitter.emit('log', { type: 'system', message: '🔑 Generating modern ED25519 key...' });
        execSync(`ssh-keygen -t ed25519 -f "${keyPath}" -N ""`, { stdio: 'ignore' });
    }
    return fs.readFileSync(`${keyPath}.pub`, 'utf8');
}

/**
 * Inyecta los archivos de activación y reglas en el directorio local seleccionado.
 */
function generateActivationFiles(sessionName, config, originalName, hasMutagen) {
    const targetDir = config.local_path;
    if (!fs.existsSync(targetDir)) {
        console.error("Target dir not found:", targetDir);
        return null;
    }

    // 1. Crear activate.sh
    const remoteExecPath = path.join(GLOBAL_BIN_DIR, 'remote-exec.sh');
    const shellHookPath = path.join(GLOBAL_BIN_DIR, 'shell-hook.sh');

    const activateContent = `
# Autogenerated by Agent Tunnel
export GEMINI_BRIDGE_SESSION="${sessionName}"
export GEMINI_BRIDGE_HOST="${config.host}"
export GEMINI_BRIDGE_PORT="${config.port || 22}"
export GEMINI_BRIDGE_USER="${config.user}"
export GEMINI_BRIDGE_HAS_MUTAGEN="${hasMutagen}"
export GEMINI_BRIDGE_PROJECT_ROOT="${targetDir}"
export GEMINI_BRIDGE_REMOTE_EXEC="${remoteExecPath}"

# Hook para intercepción de terminal (si está activo)
if [ "\${GEMINI_BRIDGE_INTERCEPT:-${globalSettings.intercept_terminal}}" = "true" ]; then
    source "${shellHookPath}"
fi

echo -e "\\x1b[36m[Agent Tunnel]\\x1b[0m Environment activated: ${originalName}"
echo -e "Remote target: ${config.user}@${config.host}"
`.trim();
    
    fs.writeFileSync(path.join(targetDir, 'activate.sh'), activateContent);
    
    // 2. Crear archivo de instrucciones (GEMINI.md o similar)
    const instrFile = globalSettings.instruction_filename || 'GEMINI.md';
    const mdContent = `
# Agent Tunnel: ${originalName}

This project is configured to work on a remote environment via SSH transparently.

## Active Configuration
- **Host:** ${config.host}
- **Port:** ${config.port || 22}
- **User:** ${config.user}
- **Remote Path:** ${config.remote_path}
- **Sync Status:** ${hasMutagen ? 'ACTIVE (Real-time)' : 'DISABLED (Direct Mode)'}

## Interception Rules (MANDATORY)
**YOU ARE FORBIDDEN** from using direct commands like \`ls\`, \`npm start\`, \`mkdir\`, etc., if they are intended for the remote machine.
Instead, **ALWAYS** prefix your terminal commands with the tunnel executor:

\`\`\`bash
${remoteExecPath} "your command here"
\`\`\`

All file operations performed locally will be synchronized to the remote machine automatically if Sync is ACTIVE.
`.trim();
    
    fs.writeFileSync(path.join(targetDir, instrFile), mdContent);
    return instrFile;
}

const server = http.createServer((req, res) => {
    // CORS: Permitir acceso desde el puerto de desarrollo de Astro (4321) y el estático (3456)
    const origin = req.headers.origin;
    if (origin && (origin.includes(':4321') || origin.includes(':3456') || origin.includes('localhost'))) {
        res.setHeader('Access-Control-Allow-Origin', origin);
    } else {
        res.setHeader('Access-Control-Allow-Origin', '*');
    }
    
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, HEAD');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Accept, Cache-Control, Last-Event-ID');
    res.setHeader('Access-Control-Allow-Credentials', 'true');

    if (req.method === 'OPTIONS') {
        res.writeHead(204);
        res.end();
        return;
    }

    if (req.method === 'HEAD') {
        res.writeHead(200);
        res.end();
        return;
    }

    // API: Settings
    if (req.url === '/api/settings' && req.method === 'GET') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(globalSettings));
        return;
    }

    if (req.url === '/api/settings' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            try {
                const newSet = JSON.parse(body);
                globalSettings = { ...globalSettings, ...newSet };
                fs.writeFileSync(SETTINGS_FILE, JSON.stringify(globalSettings, null, 2));
                logEmitter.emit('log', { type: 'system', message: `Global settings updated.` });
                res.writeHead(200); res.end(JSON.stringify({ status: 'success' }));
            } catch(e) {
                res.writeHead(400); res.end(JSON.stringify({ error: 'Invalid JSON' }));
            }
        });
        return;
    }

    // API: Configuración Principal
    if (req.url === '/api/config' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => { body += chunk; });
        req.on('end', () => {
            const config = JSON.parse(body);
            const originalSessionName = config.session_name || 'agent-tunnel';
            const validSessionName = originalSessionName.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-_]/g, '');
            const configFile = path.join(CONFIGS_DIR, `${validSessionName}.json`);
            const useMutagen = config.use_mutagen !== false; // Default a true
            const onlySave = config.only_save === true;
            
            if (onlySave) {
                logEmitter.emit('log', { type: 'system', message: `💾 Configuration saved: ${validSessionName}` });
                fs.writeFileSync(configFile, JSON.stringify(config, null, 2));
                res.writeHead(200); res.end(JSON.stringify({ status: 'success', message: 'Configuration saved.' }));
                return;
            }

            logEmitter.emit('log', { type: 'system', message: `🚀 Establishing Tunnel: ${originalSessionName} (${useMutagen ? 'SSH+Sync' : 'SSH-Only'})` });
            fs.writeFileSync(configFile, JSON.stringify(config, null, 2));

            // Inyectar archivos inmediatamente
            const injectedFile = generateActivationFiles(validSessionName, config, originalSessionName, false);
            if (injectedFile) {
                logEmitter.emit('log', { type: 'system', message: `📝 Injected ${injectedFile} and activate.sh into local folder.` });
            }

            const pubKey = ensureSshKey();
            const conn = new Client();
            
            logEmitter.emit('log', { type: 'system', message: `🔍 Checking SSH at ${config.host}:${config.port || 22}...` });

            conn.on('ready', () => {
                logEmitter.emit('log', { type: 'system', message: '✅ SSH connected. Authorizing key...' });
                
                const cleanKey = pubKey.trim();
                const setupCmd = `mkdir -p ~/.ssh && chmod 700 ~/.ssh && touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && (grep -q "${cleanKey.substring(10, 40)}" ~/.ssh/authorized_keys || echo "${cleanKey}" >> ~/.ssh/authorized_keys) && ([ -d /etc/dropbear ] && (grep -q "${cleanKey.substring(10, 40)}" /etc/dropbear/authorized_keys 2>/dev/null || echo "${cleanKey}" >> /etc/dropbear/authorized_keys) || true)`;
                
                conn.exec(setupCmd, (err2, stream2) => {
                    const finalizeSsh = () => {
                        conn.end();
                        const sshKeyPath = path.join(os.homedir(), '.ssh', 'id_ed25519_bridge');
                        const compatOpts = "-o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5";
                        const testCmd = `ssh ${compatOpts} -p ${config.port || 22} -i "${sshKeyPath}" ${config.user}@${config.host} "echo 'success'"`;
                        
                        exec(testCmd, (testErr, testStdout) => {
                            if (testErr || !testStdout.includes('success')) {
                                logEmitter.emit('log', { type: 'error', message: `❌ SSH key rejected. ${testErr ? testErr.message : 'Check authorized_keys.'}` });
                                activeSshSessions[validSessionName] = { host: config.host, user: config.user, port: config.port || 22, hasMutagen: false, warning: true };
                                generateActivationFiles(validSessionName, config, originalSessionName, false);
                                res.writeHead(200); res.end(JSON.stringify({ status: 'warning', message: 'Connected without sync (Key rejected).' }));
                                return;
                            }

                            if (!useMutagen) {
                                logEmitter.emit('log', { type: 'system', message: '✅ Key validated. SSH-Only Mode (Mutagen disabled).' });
                                activeSshSessions[validSessionName] = { host: config.host, user: config.user, port: config.port || 22, hasMutagen: false };
                                generateActivationFiles(validSessionName, config, originalSessionName, false);
                                res.writeHead(200); res.end(JSON.stringify({ status: 'success', message: 'SSH Connection established (No sync).' }));
                                return;
                            }

                            logEmitter.emit('log', { type: 'system', message: '✅ Key validated. Starting Mutagen...' });
                            exec(`mutagen sync terminate "${validSessionName}"`, () => {
                                const mutagenEnv = { ...process.env, MUTAGEN_SSH_PATH: `ssh ${compatOpts} -p ${config.port || 22} -i "${sshKeyPath}"` };
                                const mutagenProc = spawn('mutagen', [
                                    'sync', 'create', `--name=${validSessionName}`,
                                    config.local_path, `${config.user}@${config.host}:${config.remote_path}`,
                                    '--sync-mode=two-way-resolved'
                                ], { env: mutagenEnv });

                                mutagenProc.on('close', (code) => {
                                    const success = (code === 0);
                                    if (success) activeSshSessions[validSessionName] = { host: config.host, user: config.user, port: config.port || 22, hasMutagen: true };
                                    generateActivationFiles(validSessionName, config, originalSessionName, success);
                                    logEmitter.emit('log', { type: 'system', message: success ? '✨ Tunnel & Sync active!' : '⚠️ Sync failed. Direct Mode only.' });
                                    if (!res.writableEnded) {
                                        res.writeHead(200); res.end(JSON.stringify({ status: success ? 'success' : 'warning', message: 'Agent Tunnel online.' }));
                                    }
                                });
                            });
                        });
                    };
                    if (stream2) stream2.on('close', finalizeSsh).resume();
                    else finalizeSsh();
                });
            }).on('error', (err) => {
                logEmitter.emit('log', { type: 'error', message: `❌ Connection error: ${err.message}` });
                if (!res.writableEnded) {
                    res.writeHead(500); res.end(JSON.stringify({ status: 'error', message: err.message }));
                }
            }).connect({ host: config.host, port: config.port || 22, username: config.user, password: config.password, readyTimeout: 15000 });
        });
        return;
    }

    // Cleanup local files (Deactivate bridge)
    if (req.url === '/api/cleanup-local' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            try {
                const { local_path } = JSON.parse(body);
                if (local_path && fs.existsSync(local_path)) {
                    const files = ['activate.sh', globalSettings.instruction_filename || 'GEMINI.md'];
                    files.forEach(f => {
                        const p = path.join(local_path, f);
                        if (fs.existsSync(p)) fs.unlinkSync(p);
                    });
                    logEmitter.emit('log', { type: 'system', message: `🧹 Cleaned up activation files in ${local_path}` });
                }
                res.writeHead(200); res.end(JSON.stringify({ status: 'success' }));
            } catch(e) {
                res.writeHead(500); res.end(JSON.stringify({ status: 'error', message: e.message }));
            }
        });
        return;
    }

    // API: Detener Sesión
    if (req.url === '/api/stop-session' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const { name, id } = JSON.parse(body);
            const identifier = id || name.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-_]/g, '');
            
            logEmitter.emit('log', { type: 'system', message: `🛑 Terminating tunnel: ${name}...` });
            delete activeSshSessions[identifier];
            
            exec(`mutagen sync terminate "${identifier}"`, (err, stdout, stderr) => {
                if (err) {
                    logEmitter.emit('log', { type: 'error', message: `❌ Mutagen error: ${stderr || err.message}` });
                    res.writeHead(500); res.end(JSON.stringify({ status: 'error', message: stderr || err.message }));
                } else {
                    logEmitter.emit('log', { type: 'system', message: `✨ Tunnel stopped.` });
                    res.writeHead(200); res.end(JSON.stringify({ status: 'success' }));
                }
            });
        });
        return;
    }

    // Logs y SSE
    if (req.url === '/api/log' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => { 
            try {
                const data = JSON.parse(body);
                logEmitter.emit('log', data); 
                res.writeHead(200); res.end('OK');
            } catch(e) {
                console.error("⚠️  Malformed log received:", body);
                res.writeHead(400); res.end('Invalid JSON');
            }
        });
        return;
    }

    if (req.url === '/api/log-stream') {
        res.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive' });
        const listener = (msg) => res.write(`data: ${JSON.stringify(msg)}\n\n`);
        logEmitter.on('log', listener);
        req.on('close', () => logEmitter.removeListener('log', listener));
        return;
    }

    // Get configs
    if (req.url === '/api/get-configs' && req.method === 'GET') {
        const files = fs.readdirSync(CONFIGS_DIR).filter(f => f.endsWith('.json'));
        const configs = {};
        for (const file of files) {
            try { configs[file.replace('.json', '')] = JSON.parse(fs.readFileSync(path.join(CONFIGS_DIR, file), 'utf8')); } catch(e) {}
        }
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(configs));
        return;
    }

    // Test SSH
    if (req.url === '/api/test-ssh' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const config = JSON.parse(body);
            const conn = new Client();
            conn.on('ready', () => { res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ status: 'success' })); conn.end(); })
                .on('error', (err) => { res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ status: 'error', message: err.message })); })
                .connect({ host: config.host, port: config.port || 22, username: config.user, password: config.password, timeout: 5000 });
        });
        return;
    }

    // Delete saved session
    if (req.url === '/api/delete-session' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const { name } = JSON.parse(body);
            const configFile = path.join(CONFIGS_DIR, `${name}.json`);
            if (fs.existsSync(configFile)) {
                fs.unlinkSync(configFile);
                res.writeHead(200); res.end(JSON.stringify({ status: 'success' }));
            } else {
                res.writeHead(404); res.end(JSON.stringify({ status: 'error', message: 'Not found' }));
            }
        });
        return;
    }

    // LS local
    if (req.url === '/api/ls-local' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const { path: p } = JSON.parse(body);
            let target = p || process.cwd();
            
            // Si el path no existe, subir niveles hasta encontrar uno que exista
            while (target && target !== '/' && !fs.existsSync(target)) {
                target = path.dirname(target);
            }
            if (!fs.existsSync(target)) target = os.homedir();

            try {
                const dirs = fs.readdirSync(target, { withFileTypes: true })
                    .filter(f => f.isDirectory() && !f.name.startsWith('.'))
                    .map(f => f.name)
                    .sort();
                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ dirs, current: target }));
            } catch (e) { 
                res.writeHead(200, { 'Content-Type': 'application/json' }); 
                res.end(JSON.stringify({ dirs: [], current: os.homedir(), error: e.message })); 
            }
        });
        return;
    }

    // LS remote
    if (req.url === '/api/ls-remote' && req.method === 'POST') {
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', () => {
            const config = JSON.parse(body);
            const conn = new Client();
            const target = config.remote_path || '/';
            conn.on('ready', () => {
                conn.sftp((err, sftp) => {
                    if (err || !sftp) return useLsFallback(conn, target, res);
                    sftp.readdir(target, (err, list) => {
                        if (err) return useLsFallback(conn, target, res);
                        const dirs = list.filter(f => f.attrs.isDirectory() && !f.filename.startsWith('.')).map(f => f.filename).sort();
                        res.writeHead(200, { 'Content-Type': 'application/json' });
                        res.end(JSON.stringify({ dirs, current: target }));
                        conn.end();
                    });
                });
            }).on('error', (err) => { res.writeHead(200); res.end(JSON.stringify({ error: err.message })); }).connect({ host: config.host, port: config.port || 22, username: config.user, password: config.password, timeout: 5000 });
        });
        return;
    }

    // Mutagen Sessions
    if (req.url === '/api/sessions') {
        getMutagenStatus().then(output => {
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ 
                activeSsh: activeSshSessions,
                output: output
            }));
        });
        return;
    }

    // Nuevo endpoint para los logs de mutagen (pesado)
    if (req.url === '/api/mutagen-status') {
        exec('mutagen sync list', (err, stdout) => {
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ output: stdout || '' }));
        });
        return;
    }

    // Frontend Assets
    const urlPath = req.url === '/' ? '/index.html' : req.url;
    const projectPublic = path.join(__dirname, 'public', urlPath);
    
    if (fs.existsSync(projectPublic) && fs.lstatSync(projectPublic).isFile()) {
        const ext = path.extname(projectPublic);
        const mimeMap = {
            '.html': 'text/html',
            '.js': 'text/javascript',
            '.css': 'text/css',
            '.json': 'application/json',
            '.png': 'image/png',
            '.jpg': 'image/jpeg',
            '.svg': 'image/svg+xml',
            '.ico': 'image/x-icon'
        };
        res.writeHead(200, { 'Content-Type': mimeMap[ext] || 'text/plain' });
        fs.createReadStream(projectPublic).pipe(res);
        return;
    }

    res.writeHead(404); res.end();
});

function useLsFallback(conn, target, res) {
    const cmd = `ls -p "${target}" | grep / | sed 's/\\///'`;
    conn.exec(cmd, (err, stream) => {
        if (err) { res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ error: err.message })); return conn.end(); }
        let out = '';
        stream.on('data', (d) => out += d);
        stream.on('close', () => {
            const dirs = out.split('\n').map(d => d.trim()).filter(d => d && !d.startsWith('.')).sort();
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ dirs, current: target }));
            conn.end();
        }).resume();
    });
}

function startServer() {
    server.listen(PORT, () => {
        console.log(`[Agent Tunnel] online at http://localhost:${PORT}`);
    }).on('error', (err) => {
        if (err.code === 'EADDRINUSE') {
            console.log(`⚠️  Port ${PORT} in use. Forcing cleanup...`);
            try {
                // Comando multiplataforma (macOS/Linux) para matar el proceso en el puerto
                execSync(`lsof -ti :${PORT} | xargs kill -9 2>/dev/null || true`);
                console.log(`✨ Port ${PORT} freed. Retrying...`);
                // Pequeño retardo antes de reintentar
                setTimeout(() => {
                    server.listen(PORT, () => {
                        console.log(`[Agent Tunnel] online at http://localhost:${PORT}`);
                    });
                }, 1000);
            } catch (e) {
                console.error(`❌ Failed to free port ${PORT}:`, e.message);
                process.exit(1);
            }
        } else {
            console.error('Server error:', err);
            process.exit(1);
        }
    });
}

startServer();
